sso:
  sys:
    rememberMeExpireTime: 604800
  redis:
    host: 192.168.80.49
    port: 6379
    database: 0
    timeout: 100000
    pool: 
      max-active: 16
      max-wait: -1
      max-idle: 5
      min-idle: 0
    password: 123456
    #sentinel:
      #master:
      #nodes: